# Site
repository: benoitbm/my-resume
favicon: images/favicon.ico

# Content configuration version
version: 1

# Personal info
name: Benoit Boyer
title: Technical UI Designer
#email: 
website: www.benoitbm.fr

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: 
github_username:  benoitbm
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: 
linkedin_username: benoitbm
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: jekyll
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello! My name is Benoit and I'm a Technical UI Designer. As well as designing elements, with my computer science background and programming skills, I can design but also implement (or help implementing) new features. My variety of skills and empathy emphasizes teamwork and helps making the project development going smoothly.

  I am most skilled in: <mark>C++</mark> and <mark>WPF</mark>.
  
  My pronouns are: They/Them/Their

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Baldur's Gate III
        link: baldursgate3.game
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fa-solid fa-gamepad-modern
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Gather your party, and return to the Forgotten Realms in a tale of fellowship and betrayal, sacrifice and survival, and the lure of absolute power. 
        description: | # this will include new lines to allow paragraphs
          I began working of this project as a UI Developer, implementing features and UIs, using <mark>C++</mark> and <mark>WPF</mark> (with the NoesisGUI layer for the interface).
          Later on the project, I swapped roles to become a Technical UI designer, helping iterations for faster for the designs and prototypes, and making the link between the teams thanks to my knowledge of the code base.
          
      - layout: top-middle
        title: Divinity Original Sin II
        link: divinity.game
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fa-solid fa-gamepad-modern
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          The Divine is dead. The Void approaches. And the powers lying dormant within you are soon to awaken. The battle for Divinity has begun. Choose wisely and trust sparingly; darkness lurks within every heart.
        description: | # this will include new lines to allow paragraphs
          My first contribution to a video game industry as a professional! I worked on improving the UIs and improving the gamepad UIs, while implementing new quality of life tickets, fixing bugs, and improving the Razer Chroma implementation.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Larian Studios Québec
        link: larian.com
        sub_title: Technical UI Designer
        caption: August 2022 - Present
        quote: >
          Designing and implementing features (while supporting other team members)
        description: | # this will include new lines to allow paragraphs
            After being noticed on my work and my method on one of the main features I implemented for [Baldur's Gate III](https://baldursgate3.game/), I joined the UI/UX Design department as a Technical UI Designer, putting my knowledge from the code side and supporting fellow designers with this knowledge, helping with estimations and what needs to be done, while learning the ropes about UI and UX design.
            
      - layout: left
        title: Game Jam de Québec
        link: gamejamdequebec.ca
        sub_title: Co-founder
        caption: April 2022 - Present
        quote: >
          The playground of game devs in Québec City
        description: | # this will include new lines to allow paragraphs
            After the COVID-19 Pandemic, with some friends we decided to host and create a physical Game Jam within Québec City, to restore the sparks and conviviality of the video game industry in Québec City.     
            
      - layout: left
        title: Larian Studios Québec
        link: larian.com
        sub_title: UI Developer
        caption: January 2019 - August 2022
        quote: >
          Implementing UIs and game features
        description: | # this will include new lines to allow paragraphs
            My main work on [Baldur's Gate III](https://baldursgate3.game/) is implementing the User Interfaces, working closely with the designers and the other team members, always ready to give hand and feedback to improve the original designs.
            
      - layout: left
        title: Larian Studios Ghent
        link: larian.com
        sub_title: Gameplay/UI Developer internship
        caption: February 2018 - December 2018
        quote: >
          First steps in the game industry and discovering Gameplay and UI programmer jobs (and breaking my first builds).
        description: | # this will include new lines to allow paragraphs
            During my internship at Larian, I discovered how the game development works on a bigger scale, making my first implementations and contributions in [Divinity: Original Sin 2](https://divinity.game/), then later in [Baldur's Gate III](https://baldursgate3.game/).
            
      - layout: left
        title: E.C.D.C Arcadémie
        sub_title: Unity developer internship
        caption: June 2017 - July 2017
        quote: >
          Teaching while creating a video game with teenagers.
        description: | # this will include new lines to allow paragraphs
            During this facultative summer internship, we taught children and teenagers how to create a video game, showing the relation between what they're learning in school and how it can be applied in real-life cases.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Montpellier
        caption: 2016 - 2018
        sub_title: M.Sc IMAGINE
        description: | # this will include new lines to allow paragraphs
          During my time of my Master's Degree, I specialized my computer science skills into Graphics, Image Processing and Video Games development, learning mostly to manage small projects and working as a team with deadlines.
          
          Outside the university, I spent most of my free time attending to the MUUG (Montpellier Unity User Group) to attend monthly talks related to video games, and participating to any game jam I could, creating my bases for the video game industry and having a little knowledge in most of the fields that the video game industry cover, facilitating communicaiton.
      - layout: left
        title: University of the West of Scotland
        caption: 2015 - 2016
        sub_title: B.Sc Computer Game Development
        description: |
          During my time in Scotland, I learned how to handle projects and team working, as well improving my english and my communitcation skills.
          
          Outside the university, I spent most of my free time visiting Scotland, learning a new culture and discovering the world from another perspective. But mostly, spending time at the comic shop, practicing my English and playing Dungeons & Dragons, making me think, tell stories and working with a group to achieve our goals.  
      - layout: left
        title: University of Aix-Marseille
        caption: 2013 - 2015
        sub_title: 2-year undergraduate diploma in technology
        description: |
          After my A-Level in Scientific (Engineering sciences speciality), I went to do a 2-year undergraduate diploma in technology, which built my computer sciences and algorithm skills, to which I'm still using today.
          
          Outside the university, I discovered Unity and the game jams, being the first step to be in the video game industry.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my background, here are some of my other interests and hobbies:
      - Dungeons & Dragons (and other TTRPGs)
      - Gaming
      - Translating webcomics and videos
      - Writing and video editing


# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
